// This file is auto generated by running: swift run CodeGenerator
//
// The color data is derived from Version 8.0.1 downloadable here:
//    https://www.fabiocrameri.ch/colourmaps/
//
// The source file is covered by licenses:
// - Copyright (c) 2023, Fabio Crameri
//   see ScientificColourMaps8/+LICENCE.pdf
//
// - Copyright (c) 2024, Jochen Kiemes
//   see LICENSE
//
extension ScientificColorMap {
  public static func palettes() -> [ScientificColorMap] {
    [
      ScientificColorMap.acton,
      ScientificColorMap.bam,
      ScientificColorMap.bamO,
      ScientificColorMap.bamako,
      ScientificColorMap.batlow,
      ScientificColorMap.batlowK,
      ScientificColorMap.batlowW,
      ScientificColorMap.berlin,
      ScientificColorMap.bilbao,
      ScientificColorMap.broc,
      ScientificColorMap.brocO,
      ScientificColorMap.buda,
      ScientificColorMap.bukavu,
      ScientificColorMap.cork,
      ScientificColorMap.corkO,
      ScientificColorMap.davos,
      ScientificColorMap.devon,
      ScientificColorMap.fes,
      ScientificColorMap.glasgow,
      ScientificColorMap.grayC,
      ScientificColorMap.hawaii,
      ScientificColorMap.imola,
      ScientificColorMap.lajolla,
      ScientificColorMap.lapaz,
      ScientificColorMap.lipari,
      ScientificColorMap.lisbon,
      ScientificColorMap.managua,
      ScientificColorMap.navia,
      ScientificColorMap.naviaW,
      ScientificColorMap.nuuk,
      ScientificColorMap.oleron,
      ScientificColorMap.oslo,
      ScientificColorMap.roma,
      ScientificColorMap.romaO,
      ScientificColorMap.tofino,
      ScientificColorMap.tokyo,
      ScientificColorMap.turku,
      ScientificColorMap.vanimo,
      ScientificColorMap.vik,
      ScientificColorMap.vikO,
    ]
  }
  public static func categorizedPalettes() -> [ScientificColorMap] {
    [
      ScientificColorMap.acton,
      ScientificColorMap.bamako,
      ScientificColorMap.batlow,
      ScientificColorMap.batlowK,
      ScientificColorMap.batlowW,
      ScientificColorMap.bilbao,
      ScientificColorMap.buda,
      ScientificColorMap.davos,
      ScientificColorMap.devon,
      ScientificColorMap.glasgow,
      ScientificColorMap.grayC,
      ScientificColorMap.hawaii,
      ScientificColorMap.imola,
      ScientificColorMap.lajolla,
      ScientificColorMap.lapaz,
      ScientificColorMap.lipari,
      ScientificColorMap.navia,
      ScientificColorMap.naviaW,
      ScientificColorMap.nuuk,
      ScientificColorMap.oslo,
      ScientificColorMap.tokyo,
      ScientificColorMap.turku,
    ]
  }
}
