// This file is auto generated by running: swift run
//
// The source file is covered by licenses:
// Copyright (c) 2023, Fabio Crameri
// see ScientificColourMaps8/+LICENCE.pdf
//
// The color data is derived from Version 8.0.1 downloadable here:
//    https://www.fabiocrameri.ch/colourmaps/
//
// Copyright (c) 2024, Jochen Kiemes
// see LICENSE
extension ScientificColorMaps {
   public static func palettes() -> [ScientificColorMaps] {
      [
        ScientificColorMaps.bamako,
        ScientificColorMaps.lipari,
        ScientificColorMaps.naviaW,
        ScientificColorMaps.navia,
        ScientificColorMaps.cork,
        ScientificColorMaps.lapaz,
        ScientificColorMaps.oleron,
        ScientificColorMaps.tofino,
        ScientificColorMaps.turku,
        ScientificColorMaps.vik,
        ScientificColorMaps.acton,
        ScientificColorMaps.batlowW,
        ScientificColorMaps.berlin,
        ScientificColorMaps.roma,
        ScientificColorMaps.bam,
        ScientificColorMaps.lisbon,
        ScientificColorMaps.davos,
        ScientificColorMaps.bukavu,
        ScientificColorMaps.tokyo,
        ScientificColorMaps.hawaii,
        ScientificColorMaps.batlow,
        ScientificColorMaps.imola,
        ScientificColorMaps.romaO,
        ScientificColorMaps.nuuk,
        ScientificColorMaps.glasgow,
        ScientificColorMaps.grayC,
        ScientificColorMaps.fes,
        ScientificColorMaps.brocO,
        ScientificColorMaps.managua,
        ScientificColorMaps.oslo,
        ScientificColorMaps.vanimo,
        ScientificColorMaps.batlowK,
        ScientificColorMaps.vikO,
        ScientificColorMaps.corkO,
        ScientificColorMaps.buda,
        ScientificColorMaps.bilbao,
        ScientificColorMaps.lajolla,
        ScientificColorMaps.broc,
        ScientificColorMaps.devon,
        ScientificColorMaps.bamO,
      ]
   }
   public static func categorizedPalettes() -> [ScientificColorMaps] {
      [
        ScientificColorMaps.bamako,
        ScientificColorMaps.lipari,
        ScientificColorMaps.naviaW,
        ScientificColorMaps.navia,
        ScientificColorMaps.lapaz,
        ScientificColorMaps.turku,
        ScientificColorMaps.acton,
        ScientificColorMaps.batlowW,
        ScientificColorMaps.davos,
        ScientificColorMaps.tokyo,
        ScientificColorMaps.hawaii,
        ScientificColorMaps.batlow,
        ScientificColorMaps.imola,
        ScientificColorMaps.nuuk,
        ScientificColorMaps.glasgow,
        ScientificColorMaps.grayC,
        ScientificColorMaps.oslo,
        ScientificColorMaps.batlowK,
        ScientificColorMaps.buda,
        ScientificColorMaps.bilbao,
        ScientificColorMaps.lajolla,
        ScientificColorMaps.devon,
      ]
   }
}